### ISSUE TITLE
Deal with empty response from `GET inbox/`

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-logic#16]
I created a unit test where an empty inbox is mocked by returning ` ` for the `GET inbox/`.
Unexpectedly, this test fails if you make that mocked request return an empty body.
Rdflib errors with:
```sh
Inbox logic › getInboxMembers › When inbox is empty › Resolves to an empty array

    Fetcher: <https://container.com/> Not Found

      at Fetcher.failFetch (node_modules/rdflib/lib/fetcher.js:1084:17)
      at node_modules/rdflib/lib/fetcher.js:1787:26
```

A very similar test in src/util/unit.test.ts  does not fail, so not sure what I'm doing wrong here.

**Comment by michielbdejong** [comment]
After some more investigation, opened an issue upstream: https://github.com/jefflau/jest-fetch-mock/issues/189
